-- =========================================
-- Initial schema
-- =========================================

-- -----------------------------------------
-- users
-- -----------------------------------------

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(50) NOT NULL,
                       email VARCHAR(254) NOT NULL,
                       password_hash VARCHAR(255) NOT NULL,
                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       deleted_at TIMESTAMP,

                        constraint uq_users_email
                            unique (email)
);


-- -----------------------------------------
-- families
-- -----------------------------------------

CREATE TABLE families (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(100) NOT NULL,
                          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          deleted_at TIMESTAMP
);


-- -----------------------------------------
-- tags
-- -----------------------------------------

CREATE TABLE tags (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(50) NOT NULL,
                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                      CONSTRAINT uq_tags_name
                          UNIQUE (name)
);


-- -----------------------------------------
-- family_allowed_emails
-- -----------------------------------------

CREATE TABLE family_allowed_emails (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       family_id BIGINT NOT NULL,
                                       email VARCHAR(254) NOT NULL,
                                       created_by BIGINT NOT NULL,
                                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       deleted_at TIMESTAMP,

                                       CONSTRAINT uq_family_allowed_emails
                                           UNIQUE (family_id, email),

                                       CONSTRAINT fk_allowed_email_family
                                           FOREIGN KEY (family_id)
                                               REFERENCES families(id),

                                       CONSTRAINT fk_allowed_email_creator
                                           FOREIGN KEY (created_by)
                                               REFERENCES users(id)
);


-- -----------------------------------------
-- family_members
-- -----------------------------------------

CREATE TABLE family_members (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_id BIGINT NOT NULL,
                                family_id BIGINT NOT NULL,
                                role VARCHAR(20) NOT NULL,
                                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                deleted_at TIMESTAMP,

                                CONSTRAINT uq_family_member
                                    UNIQUE (user_id, family_id),

                                CONSTRAINT chk_family_members_role
                                    CHECK (role IN ('OWNER', 'MEMBER')),

                                CONSTRAINT fk_family_member_user
                                    FOREIGN KEY (user_id)
                                        REFERENCES users(id),

                                CONSTRAINT fk_family_member_family
                                    FOREIGN KEY (family_id)
                                        REFERENCES families(id)
);


-- -----------------------------------------
-- recipes
-- -----------------------------------------

CREATE TABLE recipes (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         user_id BIGINT NOT NULL,
                         family_id BIGINT NOT NULL,
                         name VARCHAR(100) NOT NULL,
                         description VARCHAR(500),
                         image_url VARCHAR(500),
                         cooked_date DATE NOT NULL,
                         visibility VARCHAR(20) NOT NULL,
                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         deleted_at TIMESTAMP,

                         CONSTRAINT chk_recipes_visibility
                             CHECK (visibility IN ('PRIVATE', 'FAMILY', 'PUBLIC')),

                         CONSTRAINT fk_recipes_user
                             FOREIGN KEY (user_id)
                                 REFERENCES users(id),

                         CONSTRAINT fk_recipes_family
                             FOREIGN KEY (family_id)
                                 REFERENCES families(id)
);


-- -----------------------------------------
-- recipe_steps
-- -----------------------------------------

CREATE TABLE recipe_steps (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              recipe_id BIGINT NOT NULL,
                              sort_order INTEGER NOT NULL,
                              description TEXT NOT NULL,
                              created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              deleted_at TIMESTAMP,

                              CONSTRAINT chk_recipe_steps_sort_order
                                  CHECK (sort_order > 0),

                              CONSTRAINT uq_recipe_steps_recipe_sort_order
                                  UNIQUE (recipe_id, sort_order),

                              CONSTRAINT fk_recipe_steps_recipe
                                  FOREIGN KEY (recipe_id)
                                      REFERENCES recipes(id)
);


-- -----------------------------------------
-- favorites
-- -----------------------------------------

CREATE TABLE favorites (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           user_id BIGINT NOT NULL,
                           recipe_id BIGINT NOT NULL,
                           created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,


                            CONSTRAINT uq_favorites_user_recipe
                                UNIQUE (user_id, recipe_id),

                           CONSTRAINT fk_favorites_user
                               FOREIGN KEY (user_id)
                                   REFERENCES users(id),

                           CONSTRAINT fk_favorites_recipe
                               FOREIGN KEY (recipe_id)
                                   REFERENCES recipes(id)
);


-- -----------------------------------------
-- recipe_tags
-- -----------------------------------------

CREATE TABLE recipe_tags (

                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             recipe_id BIGINT NOT NULL,
                             tag_id BIGINT NOT NULL,

                            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                             CONSTRAINT uq_recipe_tags
                                 UNIQUE (recipe_id, tag_id),

                             CONSTRAINT fk_recipe_tags_recipe
                                 FOREIGN KEY (recipe_id)
                                     REFERENCES recipes(id),

                             CONSTRAINT fk_recipe_tags_tag
                                 FOREIGN KEY (tag_id)
                                     REFERENCES tags(id)
);