spring.application.name=cooking-app

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cooking_app
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true